[package]
name = "nous-a1z-mqtt-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
rumqttc = { version = "0.24.0", default-features = false }
tokio = { version = "1.37.0", features = ["rt", "net", "time", "macros"] }
